//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademyG.Week6.Test.Client.ManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/AcademyG.Week6.Test.Core.Entities")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AcademyG.Week6.Test.Client.ManagementService.Order[] OrdersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientCode {
            get {
                return this.ClientCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientCodeField, value) != true)) {
                    this.ClientCodeField = value;
                    this.RaisePropertyChanged("ClientCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AcademyG.Week6.Test.Client.ManagementService.Order[] Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/AcademyG.Week6.Test.Core.Entities")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AcademyG.Week6.Test.Client.ManagementService.Client ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AcademyG.Week6.Test.Client.ManagementService.Client Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderCode {
            get {
                return this.OrderCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderCodeField, value) != true)) {
                    this.OrderCodeField = value;
                    this.RaisePropertyChanged("OrderCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode {
            get {
                return this.ProductCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeField, value) != true)) {
                    this.ProductCodeField = value;
                    this.RaisePropertyChanged("ProductCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManagementService.IManagementService")]
    public interface IManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagementService/GetAllClients", ReplyAction="http://tempuri.org/IManagementService/GetAllClientsResponse")]
        AcademyG.Week6.Test.Client.ManagementService.Client[] GetAllClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagementService/GetAllClients", ReplyAction="http://tempuri.org/IManagementService/GetAllClientsResponse")]
        System.Threading.Tasks.Task<AcademyG.Week6.Test.Client.ManagementService.Client[]> GetAllClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagementService/GetClientById", ReplyAction="http://tempuri.org/IManagementService/GetClientByIdResponse")]
        AcademyG.Week6.Test.Client.ManagementService.Client GetClientById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagementService/GetClientById", ReplyAction="http://tempuri.org/IManagementService/GetClientByIdResponse")]
        System.Threading.Tasks.Task<AcademyG.Week6.Test.Client.ManagementService.Client> GetClientByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagementService/GetClientByCode", ReplyAction="http://tempuri.org/IManagementService/GetClientByCodeResponse")]
        AcademyG.Week6.Test.Client.ManagementService.Client GetClientByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagementService/GetClientByCode", ReplyAction="http://tempuri.org/IManagementService/GetClientByCodeResponse")]
        System.Threading.Tasks.Task<AcademyG.Week6.Test.Client.ManagementService.Client> GetClientByCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagementService/AddNewClient", ReplyAction="http://tempuri.org/IManagementService/AddNewClientResponse")]
        bool AddNewClient(AcademyG.Week6.Test.Client.ManagementService.Client newClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagementService/AddNewClient", ReplyAction="http://tempuri.org/IManagementService/AddNewClientResponse")]
        System.Threading.Tasks.Task<bool> AddNewClientAsync(AcademyG.Week6.Test.Client.ManagementService.Client newClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagementService/UpdateClient", ReplyAction="http://tempuri.org/IManagementService/UpdateClientResponse")]
        bool UpdateClient(AcademyG.Week6.Test.Client.ManagementService.Client client, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagementService/UpdateClient", ReplyAction="http://tempuri.org/IManagementService/UpdateClientResponse")]
        System.Threading.Tasks.Task<bool> UpdateClientAsync(AcademyG.Week6.Test.Client.ManagementService.Client client, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagementService/DeleteClientById", ReplyAction="http://tempuri.org/IManagementService/DeleteClientByIdResponse")]
        bool DeleteClientById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManagementService/DeleteClientById", ReplyAction="http://tempuri.org/IManagementService/DeleteClientByIdResponse")]
        System.Threading.Tasks.Task<bool> DeleteClientByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IManagementServiceChannel : AcademyG.Week6.Test.Client.ManagementService.IManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManagementServiceClient : System.ServiceModel.ClientBase<AcademyG.Week6.Test.Client.ManagementService.IManagementService>, AcademyG.Week6.Test.Client.ManagementService.IManagementService {
        
        public ManagementServiceClient() {
        }
        
        public ManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AcademyG.Week6.Test.Client.ManagementService.Client[] GetAllClients() {
            return base.Channel.GetAllClients();
        }
        
        public System.Threading.Tasks.Task<AcademyG.Week6.Test.Client.ManagementService.Client[]> GetAllClientsAsync() {
            return base.Channel.GetAllClientsAsync();
        }
        
        public AcademyG.Week6.Test.Client.ManagementService.Client GetClientById(int id) {
            return base.Channel.GetClientById(id);
        }
        
        public System.Threading.Tasks.Task<AcademyG.Week6.Test.Client.ManagementService.Client> GetClientByIdAsync(int id) {
            return base.Channel.GetClientByIdAsync(id);
        }
        
        public AcademyG.Week6.Test.Client.ManagementService.Client GetClientByCode(string code) {
            return base.Channel.GetClientByCode(code);
        }
        
        public System.Threading.Tasks.Task<AcademyG.Week6.Test.Client.ManagementService.Client> GetClientByCodeAsync(string code) {
            return base.Channel.GetClientByCodeAsync(code);
        }
        
        public bool AddNewClient(AcademyG.Week6.Test.Client.ManagementService.Client newClient) {
            return base.Channel.AddNewClient(newClient);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewClientAsync(AcademyG.Week6.Test.Client.ManagementService.Client newClient) {
            return base.Channel.AddNewClientAsync(newClient);
        }
        
        public bool UpdateClient(AcademyG.Week6.Test.Client.ManagementService.Client client, int id) {
            return base.Channel.UpdateClient(client, id);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateClientAsync(AcademyG.Week6.Test.Client.ManagementService.Client client, int id) {
            return base.Channel.UpdateClientAsync(client, id);
        }
        
        public bool DeleteClientById(int id) {
            return base.Channel.DeleteClientById(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteClientByIdAsync(int id) {
            return base.Channel.DeleteClientByIdAsync(id);
        }
    }
}
